### ISSUE TITLE
Backend: Event Anwesenheitstracking 

### ISSUE THREAD

**Issue by Alfer-Star** [Campus-Consult/MemberManager#112]
Hierzu wird Frontendseitig ein QR-Code generiert, welcher den Nutzer nach der Anmeldung auf eine Seite navigiert, wo er per Nutzer Interaktion z.B. Button sein Anwesenheit bestätigt.

Die Anwesenheit soll nur einen gewissen Zeitraum aktiv sein (Dauer 2h)
Das VT bzw. die MV soll angelegt werden können und Nutzer sollen als anwesend hinterlegt werden.

**Comment by Alfer-Star** [comment]
API Events erstellen.
Events bestehen nur eine bestimmten Zeitraum 
Event enthält Anwesende Personen (Tracking Timestamp).

Personen können nachträglich vom Admin hinzugefügt und entfernt werden.

**Comment by olohr** [comment]
TODO: commands for adding/removing attendees for admins
