### ISSUE TITLE
Career Level "Alumni" and Status "Passives Mitglied" are not linked

### ISSUE THREAD

**Issue by Warner99** [Campus-Consult/MemberManager#171]
When the career level of a Member is set to "Alumni", the status should simultaneously be set to "Passives Mitglied" or at least a warning should be displayed.

**Comment by Alfer-Star** [comment]
In der Form nicht umsetzbar, weil Abhängigkeiten zwischen dynamischen Werten.
Wen Bedarf besteht dann in einem neuen Issue.
