### ISSUE TITLE
Mitglieder können Kontodaten verwalten

### ISSUE THREAD

**Issue by ngrieger** [Campus-Consult/MemberManager#45]

**Comment by Alfer-Star** [comment]
Datenschutz und rechtlich machbar? Sicherheit?
Nick ansprechen ob überhaupt noch Bedarf besteht.

**Comment by Alfer-Star** [comment]
Geschlossen wegen "nicht in Zielen 2023". Betrifft weder Engagement abbilden noch Polishing.
