### ISSUE TITLE
Dismiss from associate has wrong input description

### ISSUE THREAD

**Issue by Yorreck** [Campus-Consult/MemberManager#49]
"Select new assignee" must be "Select new career level"

**Comment by Alfer-Star** [comment]
Did update label of Dismiss Dialog and pushed changes directly into main.

Commit: ae8c83b73825a28032d9136f0746dbe24f1385c0

label are now:
- Select assignee -> Zu Entfernen
- Select new assignee -> neues Karrierelevel
- Submit Button -> Entfernen
